[2025-08-14T18:21:05.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T18:21:05.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.drop_orders_summary_if_exists manual__2025-08-14T18:20:38.447367+00:00 [queued]>
[2025-08-14T18:21:05.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.drop_orders_summary_if_exists manual__2025-08-14T18:20:38.447367+00:00 [queued]>
[2025-08-14T18:21:05.818+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T18:21:05.843+0000] {taskinstance.py:2330} INFO - Executing <Task(AthenaOperator): drop_orders_summary_if_exists> on 2025-08-14 18:20:38.447367+00:00
[2025-08-14T18:21:05.858+0000] {standard_task_runner.py:64} INFO - Started process 158 to run task
[2025-08-14T18:21:05.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'drop_orders_summary_if_exists', 'manual__2025-08-14T18:20:38.447367+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmpipfoj5xl']
[2025-08-14T18:21:05.869+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask drop_orders_summary_if_exists
[2025-08-14T18:21:06.025+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.drop_orders_summary_if_exists manual__2025-08-14T18:20:38.447367+00:00 [running]> on host 25a9e79e188f
[2025-08-14T18:21:06.308+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='drop_orders_summary_if_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T18:20:38.447367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T18:20:38.447367+00:00'
[2025-08-14T18:21:06.313+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T18:21:06.343+0000] {athena.py:132} INFO - Running Query with params:
	QueryString: 
		DROP TABLE IF EXISTS analytics.orders_summary;
	QueryExecutionContext: {'Database': 'analytics', 'Catalog': 'AwsDataCatalog'}
	ResultConfiguration: {'OutputLocation': 's3://pt-data-lab/athena-staging/'}
	WorkGroup: primary
[2025-08-14T18:21:06.374+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2025-08-14T18:21:06.375+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-08-14T18:21:06.932+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-14T18:21:08.162+0000] {athena.py:135} INFO - Query execution id: fcb267a9-f3a3-46df-81fd-2ed05d3ffb1a
[2025-08-14T18:21:08.461+0000] {waiter_with_logging.py:78} INFO - Query execution id: fcb267a9-f3a3-46df-81fd-2ed05d3ffb1a, Query is still in non-terminal state: RUNNING
[2025-08-14T18:21:12.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T18:21:12.161+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=drop_orders_summary_if_exists, run_id=manual__2025-08-14T18:20:38.447367+00:00, execution_date=20250814T182038, start_date=20250814T182105, end_date=20250814T182112
[2025-08-14T18:21:12.235+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-14T18:21:12.299+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-14T18:21:12.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
