[2025-08-14T16:58:45.614+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T16:58:45.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-14T16:58:18.948894+00:00 [queued]>
[2025-08-14T16:58:45.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-14T16:58:18.948894+00:00 [queued]>
[2025-08-14T16:58:45.649+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-14T16:58:45.664+0000] {taskinstance.py:2330} INFO - Executing <Task(AthenaOperator): ctas_orders_summary> on 2025-08-14 16:58:18.948894+00:00
[2025-08-14T16:58:45.671+0000] {standard_task_runner.py:64} INFO - Started process 64 to run task
[2025-08-14T16:58:45.676+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'ctas_orders_summary', 'manual__2025-08-14T16:58:18.948894+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmpuy9rcn59']
[2025-08-14T16:58:45.678+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask ctas_orders_summary
[2025-08-14T16:58:45.751+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.ctas_orders_summary manual__2025-08-14T16:58:18.948894+00:00 [running]> on host fa848d464678
[2025-08-14T16:58:45.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='ctas_orders_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T16:58:18.948894+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T16:58:18.948894+00:00'
[2025-08-14T16:58:45.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T16:58:45.895+0000] {athena.py:132} INFO - Running Query with params:
	QueryString: 
		
		CREATE TABLE analytics.orders_summary
		WITH (
		  format            = 'PARQUET',
		  external_location = 's3://pt-data-lab/processed-data/orders_summary/'
		) AS
		SELECT
		  customer,
		  CAST(order_date AS DATE) AS order_date,
		  COUNT(*)                 AS orders,
		  SUM(amount)              AS total_amount
		FROM analytics.raw_orders
		GROUP BY customer, CAST(order_date AS DATE);
	QueryExecutionContext: {'Database': 'analytics', 'Catalog': 'AwsDataCatalog'}
	ResultConfiguration: {'OutputLocation': 's3://pt-data-lab/athena-staging/'}
	WorkGroup: primary
[2025-08-14T16:58:45.910+0000] {base_aws.py:587} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2025-08-14T16:58:45.911+0000] {base_aws.py:164} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-08-14T16:58:46.194+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-14T16:58:47.145+0000] {athena.py:135} INFO - Query execution id: fc83cea2-2e37-4ed1-bda1-cae1961b9633
[2025-08-14T16:58:47.343+0000] {waiter_with_logging.py:78} INFO - Query execution id: fc83cea2-2e37-4ed1-bda1-cae1961b9633, Query is still in non-terminal state: QUEUED
[2025-08-14T16:58:57.892+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T16:58:57.930+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=ctas_orders_summary, run_id=manual__2025-08-14T16:58:18.948894+00:00, execution_date=20250814T165818, start_date=20250814T165845, end_date=20250814T165857
[2025-08-14T16:58:57.968+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-14T16:58:58.002+0000] {taskinstance.py:3503} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-08-14T16:58:58.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
