[2025-08-15T16:19:09.306+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-15T16:19:09.367+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_athena_pipeline.dbt_deps scheduled__2025-08-14T09:30:00+00:00 [queued]>
[2025-08-15T16:19:09.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_athena_pipeline.dbt_deps scheduled__2025-08-14T09:30:00+00:00 [queued]>
[2025-08-15T16:19:09.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-15T16:19:09.416+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-08-14 09:30:00+00:00
[2025-08-15T16:19:09.425+0000] {standard_task_runner.py:64} INFO - Started process 51 to run task
[2025-08-15T16:19:09.432+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_athena_pipeline', 'dbt_deps', 'scheduled__2025-08-14T09:30:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dbt_athena_pipeline.py', '--cfg-path', '/tmp/tmp9mr7jiaw']
[2025-08-15T16:19:09.435+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask dbt_deps
[2025-08-15T16:19:09.587+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_athena_pipeline.dbt_deps scheduled__2025-08-14T09:30:00+00:00 [running]> on host 086c8585e9f7
[2025-08-15T16:19:09.861+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_athena_pipeline' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-14T09:30:00+00:00'
[2025-08-15T16:19:09.862+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-15T16:19:09.890+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-15T16:19:09.891+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt --no-use-colors deps --profiles-dir /opt/***/.dbt']
[2025-08-15T16:19:09.913+0000] {subprocess.py:86} INFO - Output:
[2025-08-15T16:19:09.916+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-08-15T16:19:09.917+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-15T16:19:09.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-15T16:19:09.952+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-15T16:19:09.964+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_athena_pipeline, task_id=dbt_deps, run_id=scheduled__2025-08-14T09:30:00+00:00, execution_date=20250814T093000, start_date=20250815T161909, end_date=20250815T161909
[2025-08-15T16:19:09.996+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task dbt_deps (Bash command failed. The command returned a non-zero exit code 127.; 51)
[2025-08-15T16:19:10.052+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-15T16:19:10.128+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-15T16:19:10.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
