[2025-08-16T19:19:44.479+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-16T19:19:44.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_pipeline.create_external_table_if_not_exists cli__orders__20250816T191936Z [queued]>
[2025-08-16T19:19:44.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_pipeline.create_external_table_if_not_exists cli__orders__20250816T191936Z [queued]>
[2025-08-16T19:19:44.524+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-16T19:19:44.542+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): create_external_table_if_not_exists> on 2025-08-16 19:19:43+00:00
[2025-08-16T19:19:44.549+0000] {standard_task_runner.py:64} INFO - Started process 211 to run task
[2025-08-16T19:19:44.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'orders_pipeline', 'create_external_table_if_not_exists', 'cli__orders__20250816T191936Z', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/orders_pipeline.py', '--cfg-path', '/tmp/tmpbdynll7i']
[2025-08-16T19:19:44.558+0000] {standard_task_runner.py:91} INFO - Job 56: Subtask create_external_table_if_not_exists
[2025-08-16T19:19:44.643+0000] {task_command.py:426} INFO - Running <TaskInstance: orders_pipeline.create_external_table_if_not_exists cli__orders__20250816T191936Z [running]> on host 392a94efd1c1
[2025-08-16T19:19:44.829+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orders_pipeline' AIRFLOW_CTX_TASK_ID='create_external_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-08-16T19:19:43+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='cli__orders__20250816T191936Z'
[2025-08-16T19:19:44.830+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-16T19:19:44.867+0000] {credentials.py:1217} INFO - Found credentials in environment variables.
[2025-08-16T19:19:46.020+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-16T19:19:46.021+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-16T19:19:46.042+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=orders_pipeline, task_id=create_external_table_if_not_exists, run_id=cli__orders__20250816T191936Z, execution_date=20250816T191943, start_date=20250816T191944, end_date=20250816T191946
[2025-08-16T19:19:46.095+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-16T19:19:46.130+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-16T19:19:46.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
